# 2015 copyleft Serban Teodorescu 

nginx:
  extends:
    file: lib/common.yml
    service: nginx

apache:
  extends:
    file: lib/common.yml
    service: apache

ftp:
  extends:
    file: lib/common.yml
    service: ftp

fpm:
  extends:
    file: lib/common.yml
    service: fpm

mysql:
  extends:
    file: lib/common.yml
    service: mysql
