APACHE_ENVVARS=/etc/apache2/envvars
APACHE_CONF_DIR=/etc/apache2
APACHE_LOG_DIR=/srv/logs
APACHE_LOCK_DIR=/var/lock/apache2
APACHE_PID_FILE=/var/run/apache2/apache2.pid
APACHE_RUN_DIR=/var/run/apache2
APACHE_RUN_USER=www-data
APACHE_RUN_GROUP=www-data
APACHE_LYNX=/usr/bin/curl -sf
